import type { Metadata } from "next";
import { Roboto, Inter, Fascinate_Inline } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
});

const fascinateInline = Fascinate_Inline({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-fascinate-inline",
});

export const metadata: Metadata = {
  title: "Tractian • Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto.className} ${fascinateInline.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
